"""create tables

Revision ID: 028915641d17
Revises: a91f2c1a6726
Create Date: 2023-05-09 12:24:33.348089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '028915641d17'
down_revision = 'a91f2c1a6726'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
