"""all tables

Revision ID: 039de3c77fa0
Revises: 8c52d596a2d5
Create Date: 2023-05-08 13:46:02.747961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '039de3c77fa0'
down_revision = '8c52d596a2d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
