"""updated users table

Revision ID: 05fbf686a840
Revises: 7fe433c64d9b
Create Date: 2023-01-11 14:53:50.975532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05fbf686a840'
down_revision = '7fe433c64d9b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('upgrade_to', sa.String(), server_default='N/A', nullable=False))
    op.add_column('users', sa.Column('scale_to', sa.String(), server_default='N/A', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'scale_to')
    op.drop_column('users', 'upgrade_to')
    # ### end Alembic commands ###
