"""create payouts table

Revision ID: 0663b6a209ed
Revises: a1e92891e1c1
Create Date: 2023-01-12 16:33:41.450327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0663b6a209ed'
down_revision = 'a1e92891e1c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payouts', sa.Column('reason', sa.String(), server_default='N/A', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payouts', 'reason')
    # ### end Alembic commands ###
