"""capital cryptochil

Revision ID: 0bcbd81048df
Revises: 89bb959d450f
Create Date: 2023-05-07 01:24:02.679496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bcbd81048df'
down_revision = '89bb959d450f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('transaction_id', sa.String(), nullable=False))
    op.add_column('users', sa.Column('transaction_link', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'users', ['transaction_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'transaction_link')
    op.drop_column('users', 'transaction_id')
    # ### end Alembic commands ###
