"""update requests

Revision ID: 17e4c61d01b0
Revises: 8ab221f44bf8
Create Date: 2023-01-09 23:19:48.276063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17e4c61d01b0'
down_revision = '8ab221f44bf8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
