"""users profit_share

Revision ID: 1dea16c89cea
Revises: d483fedd0ad6
Create Date: 2023-06-26 18:53:06.631803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dea16c89cea'
down_revision = 'd483fedd0ad6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'profit_split')
    # ### end Alembic commands ###
