"""updating users table

Revision ID: 1e262ea5bee9
Revises: 71d08e789610
Create Date: 2023-01-08 00:43:00.926254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e262ea5bee9'
down_revision = '71d08e789610'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('serial_no', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('metatrader_password', sa.String(), server_default='N/A', nullable=False))
    op.drop_column('users', 'password')
    op.drop_column('users', 'metatrader_pass')
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('metatrader_pass', sa.VARCHAR(), server_default=sa.text("'N/A'::character varying"), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'metatrader_password')
    op.drop_column('users', 'serial_no')
    # ### end Alembic commands ###
