"""Create new tables

Revision ID: 216989849c90
Revises: 3c0592b8b6d7
Create Date: 2023-05-25 22:17:56.264605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '216989849c90'
down_revision = '3c0592b8b6d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
