"""users profit_share

Revision ID: 24a5aeaa8073
Revises: d3185effff5f
Create Date: 2023-06-26 21:30:22.639490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24a5aeaa8073'
down_revision = 'd3185effff5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payouts', sa.Column('payable_amount', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('profit_split', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profit_split')
    op.drop_column('payouts', 'payable_amount')
    # ### end Alembic commands ###
