"""Drop table users

Revision ID: 3d07fb71e4be
Revises: 85dd8c665c59
Create Date: 2023-06-25 00:11:12.611537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d07fb71e4be'
down_revision = '85dd8c665c59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('requests')
    op.drop_table('payouts')
    op.drop_table('Cryptochil')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
