"""phone number type

Revision ID: 3df171273094
Revises: 9cf6a59d3c3f
Create Date: 2023-01-04 16:19:07.679251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3df171273094'
down_revision = '9cf6a59d3c3f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
