"""create Admin table

Revision ID: 3ff474f5cdc1
Revises: d3a05154a6f9
Create Date: 2023-01-13 14:50:23.402017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ff474f5cdc1'
down_revision = 'd3a05154a6f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
