"""add type column to requests

Revision ID: 497472bbd633
Revises: 92c0cdf83476
Create Date: 2023-01-09 16:07:55.789774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '497472bbd633'
down_revision = '92c0cdf83476'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('type', sa.String(), server_default='N/A', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'type')
    # ### end Alembic commands ###
