"""update user

Revision ID: 549bed6103bc
Revises: a8d11f0d5db1
Create Date: 2023-01-06 22:08:40.272654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '549bed6103bc'
down_revision = 'a8d11f0d5db1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('metatrader_pass', sa.String(), server_default='N/A', nullable=False))
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'mt_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mt_password', sa.VARCHAR(), server_default=sa.text("'N/A'::character varying"), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('users', 'metatrader_pass')
    # ### end Alembic commands ###
