"""drop all tables

Revision ID: 580874367efe
Revises: 24a5aeaa8073
Create Date: 2023-06-26 21:44:11.331937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '580874367efe'
down_revision = '24a5aeaa8073'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('requests')
    op.drop_table('payouts')
    op.drop_table('Cryptochil')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
