"""create tables

Revision ID: 594ec89e4ed3
Revises: fa3f952e3955
Create Date: 2023-05-06 21:28:59.425114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '594ec89e4ed3'
down_revision = 'fa3f952e3955'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
