"""add firstName and lastName to Payout

Revision ID: 5c23b0c92b92
Revises: 0809c8ee8ec0
Create Date: 2023-02-12 23:29:38.417988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c23b0c92b92'
down_revision = '0809c8ee8ec0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
