"""create payouts table

Revision ID: 62e73f056189
Revises: d084d90f579f
Create Date: 2023-01-12 16:03:36.016694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62e73f056189'
down_revision = 'd084d90f579f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payouts', sa.Column('amount', sa.Integer(), nullable=False))
    op.drop_column('payouts', 'Amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payouts', sa.Column('Amount', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('payouts', 'amount')
    # ### end Alembic commands ###
