"""users profit_share

Revision ID: 6683e1a859d8
Revises: 7b1a983fe694
Create Date: 2023-06-26 19:15:14.099567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6683e1a859d8'
down_revision = '7b1a983fe694'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('payouts')
    # ### end Alembic commands ###
