"""create payouts table

Revision ID: 6d20784ed079
Revises: a7ca279dada3
Create Date: 2023-01-12 16:20:26.896230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d20784ed079'
down_revision = 'a7ca279dada3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
