"""add type and account id metatrader to users table

Revision ID: 75c3f8a440fe
Revises: ba80948a4cf7
Create Date: 2023-01-16 01:05:48.409198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75c3f8a440fe'
down_revision = 'ba80948a4cf7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('account_id_meta', sa.String(), server_default='N/A', nullable=False))
    op.add_column('users', sa.Column('type_meta', sa.String(), server_default='N/A', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'type_meta')
    op.drop_column('users', 'account_id_meta')
    # ### end Alembic commands ###
