"""users profit_share

Revision ID: 7b1a983fe694
Revises: e8a2bf423a6b
Create Date: 2023-06-26 19:10:47.134522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b1a983fe694'
down_revision = 'e8a2bf423a6b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'profit_split')
    op.drop_column('payouts', 'payable_amount')
    # ### end Alembic commands ###
