"""Drop table users

Revision ID: 7cd783018a3b
Revises: fc237b133f59
Create Date: 2023-05-25 07:39:42.615021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cd783018a3b'
down_revision = 'fc237b133f59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
