"""updated users table

Revision ID: 7fe433c64d9b
Revises: 90edcb3f40a7
Create Date: 2023-01-11 14:28:28.301889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fe433c64d9b'
down_revision = '90edcb3f40a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status_upgrade', sa.String(), server_default='N/A', nullable=False))
    op.add_column('users', sa.Column('status_scale', sa.String(), server_default='N/A', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status_scale')
    op.drop_column('users', 'status_upgrade')
    # ### end Alembic commands ###
