"""create tables

Revision ID: 81d390a56f45
Revises: 97d19929b08b
Create Date: 2023-06-24 23:50:25.656553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81d390a56f45'
down_revision = '97d19929b08b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
  pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
