"""capital cryptochil

Revision ID: 89bb959d450f
Revises: 9b54f27c53e3
Create Date: 2023-05-06 22:51:48.237626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89bb959d450f'
down_revision = '9b54f27c53e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Cryptochil_profile_id_key', 'Cryptochil', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('Cryptochil_profile_id_key', 'Cryptochil', ['profile_id'])
    # ### end Alembic commands ###
