"""add type column payment as default

Revision ID: 8ab221f44bf8
Revises: 497472bbd633
Create Date: 2023-01-09 16:14:27.826468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ab221f44bf8'
down_revision = '497472bbd633'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
