"""create new users and request table

Revision ID: 8be3f053e850
Revises: 1ff37030846e
Create Date: 2023-01-10 15:12:54.215585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8be3f053e850'
down_revision = '1ff37030846e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
