"""all tables

Revision ID: 8c52d596a2d5
Revises: ec7932f58f92
Create Date: 2023-05-08 13:44:35.838614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c52d596a2d5'
down_revision = 'ec7932f58f92'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
