"""updated requests table

Revision ID: 90edcb3f40a7
Revises: d2e4038e2159
Create Date: 2023-01-11 13:41:57.354457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90edcb3f40a7'
down_revision = 'd2e4038e2159'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('requests_email_key', 'requests', type_='unique')
    op.drop_constraint('requests_phone_no_key', 'requests', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('requests_phone_no_key', 'requests', ['phone_no'])
    op.create_unique_constraint('requests_email_key', 'requests', ['email'])
    # ### end Alembic commands ###
