"""capital cryptochil

Revision ID: 9b54f27c53e3
Revises: b57c62f12e4b
Create Date: 2023-05-06 22:22:25.092462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b54f27c53e3'
down_revision = 'b57c62f12e4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Cryptochil', 'capital')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Cryptochil', sa.Column('capital', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
