"""capital cryptochil

Revision ID: 9ddd03a1e443
Revises: 594ec89e4ed3
Create Date: 2023-05-06 21:49:37.112655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ddd03a1e443'
down_revision = '594ec89e4ed3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Cryptochil', sa.Column('capital', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Cryptochil', 'capital')
    # ### end Alembic commands ###
