"""add server default to requests

Revision ID: a1a174fb2151
Revises: 8f8c74ddf42d
Create Date: 2023-01-07 22:58:06.125252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1a174fb2151'
down_revision = '8f8c74ddf42d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
