"""create payouts table

Revision ID: a1e92891e1c1
Revises: 6d20784ed079
Create Date: 2023-01-12 16:23:24.669961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1e92891e1c1'
down_revision = '6d20784ed079'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payouts',
    sa.Column('serial_no', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=False),
    sa.Column('amount', sa.String(), nullable=False),
    sa.Column('analytics', sa.String(), nullable=False),
    sa.Column('profit_share', sa.String(), server_default='N/A', nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('wallet_address', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('serial_no')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payouts')
    # ### end Alembic commands ###
