"""capital cryptochil

Revision ID: a5e7c7e3292c
Revises: b002f1f659e9
Create Date: 2023-05-08 13:19:28.522995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5e7c7e3292c'
down_revision = 'b002f1f659e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
