"""create payouts table

Revision ID: a7ca279dada3
Revises: df96d69e2f4a
Create Date: 2023-01-12 16:15:52.041411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7ca279dada3'
down_revision = 'df96d69e2f4a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
