"""update user

Revision ID: a8d11f0d5db1
Revises: 68439c92dd8b
Create Date: 2023-01-06 16:14:42.320223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8d11f0d5db1'
down_revision = '68439c92dd8b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(), server_default='N/A', nullable=False))
    op.add_column('users', sa.Column('capital', sa.String(), server_default ='N/A', nullable=False))
    op.add_column('users', sa.Column('phase', sa.String(), server_default='N/A', nullable=False))
    op.add_column('users', sa.Column('mt_login', sa.String(), server_default='N/A', nullable=False))
    op.add_column('users', sa.Column('mt_password', sa.String(), server_default='N/A', nullable=False))
    op.add_column('users', sa.Column('mt_server', sa.String(), server_default='N/A', nullable=False))
    op.add_column('users', sa.Column('analytics', sa.String(), server_default='N/A', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'analytics')
    op.drop_column('users', 'mt_server')
    op.drop_column('users', 'mt_password')
    op.drop_column('users', 'mt_login')
    op.drop_column('users', 'phase')
    op.drop_column('users', 'capital')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
