"""all tables

Revision ID: a91f2c1a6726
Revises: 039de3c77fa0
Create Date: 2023-05-08 13:49:59.998677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a91f2c1a6726'
down_revision = '039de3c77fa0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'serial_no')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('serial_no', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
