"""capital cryptochil

Revision ID: b57c62f12e4b
Revises: 9ddd03a1e443
Create Date: 2023-05-06 22:06:21.552808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b57c62f12e4b'
down_revision = '9ddd03a1e443'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Cryptochil', 'capital',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Cryptochil', 'capital',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
