"""updated users table

Revision ID: bce05c58369d
Revises: 62e73f056189
Create Date: 2023-01-12 16:04:24.813177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bce05c58369d'
down_revision = '62e73f056189'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payouts', sa.Column('wallet_address', sa.Integer(), nullable=False))
    op.drop_column('payouts', 'wallet_Address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payouts', sa.Column('wallet_Address', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('payouts', 'wallet_address')
    # ### end Alembic commands ###
