"""auto create user

Revision ID: c903c590e83b
Revises: 3ad621589781
Create Date: 2022-10-25 01:17:45.511120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c903c590e83b'
down_revision = '3ad621589781'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
