"""create tables

Revision ID: cb046ac59a36
Revises: 81d390a56f45
Create Date: 2023-06-24 23:55:11.106419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb046ac59a36'
down_revision = '81d390a56f45'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
