"""removed serial no from requests

Revision ID: cd69c06a2d5e
Revises: f540fc264d8f
Create Date: 2023-01-07 22:46:41.636258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd69c06a2d5e'
down_revision = 'f540fc264d8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'serial_no')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('serial_no', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
