"""added reason to users table

Revision ID: d2e4038e2159
Revises: 9abd3ba33948
Create Date: 2023-01-10 15:54:20.913417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2e4038e2159'
down_revision = '9abd3ba33948'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reason', sa.String(), server_default='N/A', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reason')
    # ### end Alembic commands ###
