"""users profit_share

Revision ID: d3185effff5f
Revises: 2cb4fbe35a6a
Create Date: 2023-06-26 20:12:28.970740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3185effff5f'
down_revision = '2cb4fbe35a6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('payouts')
    # ### end Alembic commands ###
