"""create new users

Revision ID: d6133bea56f7
Revises: bcf88f6b9c98
Create Date: 2023-01-10 15:30:34.563998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6133bea56f7'
down_revision = 'bcf88f6b9c98'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
