"""capital cryptochil

Revision ID: d6e91ae6f464
Revises: a5e7c7e3292c
Create Date: 2023-05-08 13:21:30.381929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6e91ae6f464'
down_revision = 'a5e7c7e3292c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('serial_no', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'serial_no')
    # ### end Alembic commands ###
