"""Drop table users

Revision ID: e5c194ea8fc8
Revises: 5de2219a9ec1
Create Date: 2023-05-25 22:51:42.851646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5c194ea8fc8'
down_revision = '5de2219a9ec1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
