"""users profit_share

Revision ID: e8a2bf423a6b
Revises: 1dea16c89cea
Create Date: 2023-06-26 18:59:00.598787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8a2bf423a6b'
down_revision = '1dea16c89cea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'profit_split')
    op.drop_column('payouts', 'payable_amount')
    # ### end Alembic commands ###
