"""add payment to requests

Revision ID: e8c17057fea1
Revises: fcaa6ed07d35
Create Date: 2023-02-11 16:26:14.354905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8c17057fea1'
down_revision = 'fcaa6ed07d35'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('transaction_id', sa.String(), server_default='N/A', nullable=False))
    op.add_column('requests', sa.Column('transaction_link', sa.String(), server_default='N/A', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'transaction_link')
    op.drop_column('requests', 'transaction_id')
    # ### end Alembic commands ###
