"""all tables

Revision ID: ec7932f58f92
Revises: fc0e70720360
Create Date: 2023-05-08 13:41:15.512407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec7932f58f92'
down_revision = 'fc0e70720360'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_serial_no_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_serial_no_key', 'users', ['serial_no'])
    # ### end Alembic commands ###
