"""add firstName and lastName to Payout

Revision ID: f1cda2016b69
Revises: 5c23b0c92b92
Create Date: 2023-02-12 23:32:46.123297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1cda2016b69'
down_revision = '5c23b0c92b92'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payouts', sa.Column('first_name', sa.String(), server_default='N/A', nullable=False))
    op.add_column('payouts', sa.Column('last_name', sa.String(), server_default='N/A', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payouts', 'last_name')
    op.drop_column('payouts', 'first_name')
    # ### end Alembic commands ###
