"""add transaction_id to requests

Revision ID: f540fc264d8f
Revises: 0c811fe953f4
Create Date: 2023-01-07 22:41:56.426468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f540fc264d8f'
down_revision = '0c811fe953f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('transaction_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'transaction_id')
    # ### end Alembic commands ###
