"""craeting users table

Revision ID: f9104aaf3017
Revises: 450a7ca42a43
Create Date: 2023-01-08 01:24:39.298042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9104aaf3017'
down_revision = '450a7ca42a43'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
