"""add payment to requests

Revision ID: fcaa6ed07d35
Revises: 75c3f8a440fe
Create Date: 2023-02-11 16:23:31.695948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcaa6ed07d35'
down_revision = '75c3f8a440fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
